package com.asbobryakov.flink_spring.config;

import com.asbobryakov.flink_spring.schema.kafka.AlertMessage;
import com.asbobryakov.flink_spring.schema.kafka.ClickMessage;
import com.asbobryakov.flink_spring.schema.kafka.TriggerMessage;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class FlinkConfig {

    @Bean
    public StreamExecutionEnvironment streamExecutionEnvironment() {
        final var env = StreamExecutionEnvironment.getExecutionEnvironment();
        env.getConfig().disableAutoGeneratedUIDs();
        registerKryoTypes(env);
        return env;
    }

    private void registerKryoTypes(StreamExecutionEnvironment env) {
        env.getConfig().registerKryoType(ClickMessage.class);
        env.getConfig().registerKryoType(TriggerMessage.class);
        env.getConfig().registerKryoType(AlertMessage.class);
    }
}
