package com.asbobryakov.flink_spring.config;

import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class FlinkConfig {

    @Bean
    public StreamExecutionEnvironment streamExecutionEnvironment() {
        final var env = StreamExecutionEnvironment.getExecutionEnvironment();
        env.getConfig().disableAutoGeneratedUIDs();
        return env;
    }
}
