flink:
  app-name: flink-spring
  submit-jobs-on-app-start: true

jobs:
  click-to-product-job:
    enabled: false
    operators:
      deduplicator:
        ttl:
          app: 7d
  trigger-to-alert-job:
    enabled: false
    state-waiting: 10m

kafka:
  group-id: group_id
  bootstrap-servers: localhost:29092
  topics:
    click-topic: 'click-topic'
    trigger-topic: 'trigger-topic'
    alert-topic: 'alert-topic'