version: '3.9'

services:
  jobmanager:
    image: flink:1.17.0-scala_2.12-java11
    ports:
      - '8081:8081'
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
    command:
      - jobmanager

  taskmanager:
    image: flink:1.17.0-scala_2.12-java11
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
    command:
      - taskmanager